---
# [NEXTCLOUD CONFIG]
nextcloud_trusted_domain:
  - "my-nextcloud-test.mydom.ro" #Domain name
  - "{{ ansible_host }}" #Local IP address
nextcloud_instance_name: "{{ nextcloud_trusted_domain | first }}"
nextcloud_trusted_proxies:
  - "<external_load_balancer_ip>" #External load balancer IP -> Optional (leave empty if not needed)

# [PHP CONFIG]
php_ver: "8.3"
php_dir: "/etc/php/{{ php_ver }}"
php_socket: "/run/php/php{{ php_ver }}-fpm.sock"
php_memory_limit: 512M
php_pkg_spe:
  - "php{{ php_ver }}-ctype"
  - "php{{ php_ver }}-curl"
  - "php{{ php_ver }}-dom"
  - "php{{ php_ver }}-fileinfo"
  - "php{{ php_ver }}-gd"
  - "php{{ php_ver }}-xml"
  - "php{{ php_ver }}-posix"
  - "php{{ php_ver }}-simplexml"
  - "php{{ php_ver }}-xmlreader"
  - "php{{ php_ver }}-xmlwriter"
  - "php{{ php_ver }}-zip"
  - "php{{ php_ver }}-intl"
  - "php{{ php_ver }}-ldap"
  - "php{{ php_ver }}-smbclient"
  - "php{{ php_ver }}-ftp"
  - "php{{ php_ver }}-imap"
  - "php{{ php_ver }}-bcmath"
  - "php{{ php_ver }}-gmp"
  - "php{{ php_ver }}-exif"
  - "php{{ php_ver }}-apcu"
  - "php{{ php_ver }}-memcached"
  - "php{{ php_ver }}-redis"
  - "php{{ php_ver }}-mbstring"
  - "php{{ php_ver }}-imagick"

# [NGINX CONFIG]
nextcloud_websrv: "nginx"
nextcloud_install_tls: true
nextcloud_tls_enforce: true
nextcloud_tls_cert_file: "/etc/ssl/private/nextcloud.crt"
nextcloud_tls_cert_key_file: "/etc/ssl/private/nextcloud.key"
nextcloud_tls_src_cert: "files/cert.crt" #Local Playbook path
nextcloud_tls_src_cert_key: "files/cert.key" #Local Playbook path
nextcloud_ipv6: false
nextcloud_tls_session_cache_size: 50m 
nextcloud_tls_dhparam: "/etc/ssl/dhparam.pem"
nextcloud_mozilla_modern_ssl_profile : false
nextcloud_hsts: false
nextcloud_max_upload_size: 512m

# [REDIS CONFIG]
nextcloud_redis_host: '/var/run/redis/redis.sock'
nextcloud_redis_port: 0

# [DATABASE CONFIG]
nextcloud_db_host: "127.0.0.1"
nextcloud_db_backend: "mysql"
nextcloud_db_enabled_on_startup: true
nextcloud_db_name: "nextcloud"
nextcloud_db_admin: "ncadmin" #Modify this  -> use ansible vault
nextcloud_db_pwd: "placintebune"  #Modify this  -> use ansible vault
nextcloud_mysql_root_pwd_update: true
nextcloud_mysql_root_pwd: "placintebune" #Modify this  -> use ansible vault
mysql_daemon: "mysql" 

# [NEXTCLOUD CONFIG] 
nextcloud_data_dir: "/data" #Data mount point
nextcloud_webroot: "/opt/nextcloud"
nextcloud_admin_name: "admin"
nextcloud_admin_pwd: "placintebune" #Modify this -> use ansible vault

#Variables for the nextcloud data mount point -> Optional if /data is not on a separate disk
nextcloud_data_device: /dev/vdb
nextcloud_data_partition: /dev/vdb1
nextcloud_data_fstype: xfs

nextcloud_config_settings:
  - { name: 'default_phone_region', value: 'RO' }
  - { name: 'overwrite.cli.url', value: 'https://{{ nextcloud_trusted_domain | first }}' }
  - { name: 'memcache.local', value: '\OC\Memcache\APCu' }
  - { name: 'mysql.utf8mb4', value: true }
  - { name: 'updater.release.channel', value: 'production' }
nextcloud_redis_settings:
  - { name: 'redis host', value: "{{ nextcloud_redis_host }}" }
  - { name: 'redis port', value: "{{ nextcloud_redis_port }}" }
  - { name: 'maintenance_window_start', value: '2' }
  - { name: 'memcache.locking', value: '\OC\Memcache\Redis' }
  - { name: 'mail_smtpmode', value: 'smtp' }
  - { name: 'mail_smtphost', value: '127.0.0.1' } #Modify this
  - { name: 'mail_sendmailmode', value: 'smtp' }
  - { name: 'mail_smtpport', value: '25' }
  - { name: 'mail_from_address', value: 'noreply' }
  - { name: 'mail_domain', value: 'mydom_mail.com' }  #Modify this

nextcloud_apps:
  - { name: accessibility }
  - { name: activity }
  - { name: admin_audit }
  - { name: bruteforcesettings }
  - { name: calendar }
  - { name: cloud_federation_api }
  - { name: comments }
  - { name: contacts }
  - { name: contactsinteraction }
  - { name: dashboard }
  - { name: dav }
  - { name: documentserver_community }
  - { name: encryption }
  - { name: federatedfilesharing }
  - { name: federation }
  - { name: files }
  - { name: files_external }
  - { name: files_pdfviewer }
  - { name: files_rightclick }
  - { name: files_sharing }
  - { name: files_trashbin }
  - { name: files_versions }
  - { name: files_videoplayer }
  - { name: firstrunwizard }
  - { name: forms }
  - { name: groupfolders }
  - { name: logreader }
  - { name: metadata }
  - { name: monitoring }
  - { name: lookup_server_connector }
  - { name: nextcloud_announcements }
  - { name: notes }
  - { name: notifications }
  - { name: pdfviewer }
  - { name: oauth2 }
  - { name: onlyoffice }
  - { name: password_policy }
  - { name: photos }
  - { name: privacy }
  - { name: provisioning_api }
  - { name: recommendations }
  - { name: related_resources }
  - { name: serverinfo }
  - { name: settings }
  - { name: sharebymail }
  - { name: spreed }
  - { name: support }
  - { name: survey_client }
  - { name: systemtags }
  - { name: text }
  - { name: theming }
  - { name: theming_customcss }
  - { name: twofactor_admin }
  - { name: twofactor_backupcodes }
  - { name: twofactor_totp }
  - { name: updatenotification }
  - { name: user_ldap }
  - { name: user_status }
  - { name: viewer }
  - { name: weather_status }
  - { name: workflowengine }