- name: Stop & disable ufw.
  service:
    name: ufw
    state: stopped
    enabled: False

- name: Update apt
  apt: update_cache=yes

- name: Enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present
    reload: yes
    ignoreerrors: yes    

- name: Enable net.core.somaxcon in sysctl
  sysctl:
    name: net.core.somaxconn
    value: '512'
    state: present
    reload: yes
    ignoreerrors: yes

- name: Disable transparent hugepages
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
  become: yes

- name: Create directory redis in etc
  become: yes
  file: 
    path: /etc/redis
    state: directory
    mode: '0755'

- name: Unarchive redis
  become: yes
  unarchive: 
    src: https://github.com/redis/redis/archive/refs/tags/7.4.2.tar.gz
    remote_src: yes
    dest: /tmp

- name: Copy directory to etc
  become: yes
  copy:
    src: /tmp/redis-7.4.2/
    dest: /etc/redis/
    remote_src: yes
    directory_mode: yes

- name: Remove tmp archive
  become: yes
  file:
    path: /tmp/redis-7.4.2
    state: absent    

- name: Install packages 
  become: yes
  apt:
    name: "{{ item }}" 
    state: latest
  loop:
    - build-essential
    - tar
    - make 
    - libsystemd-dev
    - libhiredis-dev
    - libssl-dev
    - liblua5.4-dev
    - libjemalloc-dev

- name: Make 
  become: yes
  make: 
    chdir: /etc/redis
    file: /etc/redis/Makefile

- name: Make install 
  become: yes
  make: 
    chdir: /etc/redis
    file: /etc/redis/Makefile
    target: install
