- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart zookeeper
  systemd:
    name: zookeeper
    state: restarted

- name: Restart kafka
  systemd:
    name: kafka
    state: restarted
