- name: nginx-restart
  service:
    name: nginx
    state: restarted

- name: nginx-stop
  service:
    name: nginx
    state: stopped

- name: nginx-start
  service:
    name: nginx
    state: started
