- debug:
    msg: "This task is running on {{ inventory_hostname }} ({{ ansible_host }})"

- name: Ensure required packages are installed
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages|default([]) }}"

- name: Upgrade all packages
  apt: upgrade=dist

- name: Ensure chrony is enabled and started
  systemd:
    name: chrony
    enabled: yes
    state: started

- name: Set timezone to {{ timezone }}
  command: timedatectl set-timezone {{ timezone }}
  when: timezone is defined and timezone != ""
  become: true

- name: Set nofile limits
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file"
              state=present
              line="{{ item }}"
  with_items:
    - "* soft nofile 32768"
    - "* hard nofile 32768"

- name: Set nproc limits
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf
              insertafter=EOF
              state=present
              create=yes
              line="{{ item }}"
              mode=0644
  with_items:
    - "* soft nproc 32768"
    - "* hard nproc 32768"

- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=1 state=present ignoreerrors=yes

- name: Disable THP until reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  become: true
  ignore_errors: yes

- name: Disable THP permanently in GRUB
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash transparent_hugepage=never"'
    backrefs: yes
  become: true

- name: Update GRUB config
  command: update-grub
  become: true

- name: Install selected Java version
  apt:
    name: "openjdk-{{ java_version }}-jdk"
    state: present
    update_cache: yes
